package com.nsr.movierating.model;

import java.util.List;
import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "userRatings")
public class Rating {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String userId;
	@DynamoDBAttribute
	private List<Map<String,Integer>>  movieRatingList;

	public Rating() {}
	
	public Rating(String userId, List<Map<String, Integer>> movieRatingList) {
		super();
		this.userId = userId;
		this.movieRatingList = movieRatingList;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public List<Map<String, Integer>> getMovieRatingList() {
		return movieRatingList;
	}

	public void setMovieRatingList(List<Map<String, Integer>> movieRatingList) {
		this.movieRatingList = movieRatingList;
	}
	
	
	
	
}
